spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        database-platform: org.hibernate.dialect.H2Dialect
    jpa:
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled=true:
logging:
    level:
        org.hibernate.SQL: DEBUG
        org.springframework: INFO